import os
import json
import asyncpg
import logging

log = logging.getLogger("db")

# Read Neon Connection String from your server environment variables
DATABASE_URL = os.getenv("DATABASE_URL")

async def get_db_connection():
    """Establishes an SSL connection to Neon.tech."""
    if not DATABASE_URL:
        raise ValueError("DATABASE_URL environment variable is missing!")
    return await asyncpg.connect(DATABASE_URL, ssl="require")

async def add_order(user_id: int, username: str | None, name: str, address: str, items: list[dict], total: float) -> int:
    """Inserts a dynamic new checkout order inside Neon PostgreSQL."""
    conn = None
    try:
        conn = await get_db_connection()
        items_json = json.dumps(items, ensure_ascii=False)
        
        query = """
            INSERT INTO orders (user_id, username, client_name, address, items, total_price)
            VALUES ($1, $2, $3, $4, $5, $6)
            RETURNING id;
        """
        order_id = await conn.fetchval(query, user_id, username, name, address, items_json, total)
        return order_id
    except Exception as e:
        log.error(f"PostgreSQL insertion breakdown: {e}")
        return 0
    finally:
        if conn:
            await conn.close()

async def list_user_orders(user_id: int, limit: int = 5) -> list:
    """Fetches historical records of orders generated by a distinct User Account ID."""
    conn = None
    try:
        conn = await get_db_connection()
        query = """
            SELECT id, total_price as total 
            FROM orders 
            WHERE user_id = $1 
            ORDER BY id DESC 
            LIMIT $2;
        """
        rows = await conn.fetch(query, user_id, limit)
        return rows
    except Exception as e:
        log.error(f"PostgreSQL fetch query execution exception: {e}")
        return []
    finally:
        if conn:
            await conn.close()